# Generated by Django 4.0 on 2021-12-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hourplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hourplanner.division')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourplanner.employee')),
            ],
        ),
    ]
